# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more
# letter at a random position. Return the letter that was added to t.

from collections import Counter

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        return list(Counter(t) - Counter(s))[0]

# Main section
sol = Solution()
for s, t in [
               ('abcd', 'abcde'),
               ('', 'y'),
               ('abcdefghijklmnopqrstuvwxyz', 'abcdefghijklmnopqrstuvwxyza'),
               ('aaaaa', 'aaaaaa'),
               ('aaaaa', 'baaaaa'),
            ]:
    print(f's = {s} ; t = {t}')
    r = sol.findTheDifference(s, t)
    print(f'r = {r}')
    print('======================')

