# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more
# letter at a random position. Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # Using string method: replace. When the 3rd argument (count) is
        # passed, then only count occurrences are replaced in the string.
        for c in s:
            t = t.replace(c,'',1)
        return t

# Main section
sol = Solution()
for s, t in [
               ('abcd', 'abcde'),
               ('', 'y'),
               ('abcdefghijklmnopqrstuvwxyz', 'abcdefghijklmnopqrstuvwxyza'),
               ('aaaaa', 'aaaaaa'),
               ('aaaaa', 'baaaaa'),
            ]:
    print(f's = {s} ; t = {t}')
    r = sol.findTheDifference(s, t)
    print(f'r = {r}')
    print('======================')


